-- Insert a sample project for testing
INSERT INTO projects (
  title,
  description,
  location,
  address,
  category,
  latitude,
  longitude,
  thumbnail_url,
  hero_image_url,
  model_url,
  rating,
  review_count,
  online_visitors,
  total_visitors,
  virtual_tours,
  highlights,
  visitor_tips,
  marketplace_links,
  badges,
  is_published
) VALUES (
  'Taj Mahal Virtual Experience',
  'Experience the breathtaking beauty of the Taj Mahal, one of the Seven Wonders of the World, through our immersive 3D virtual tour. Explore every intricate detail of this magnificent marble mausoleum from the comfort of your home.',
  'Agra, India',
  'Dharmapuri, Forest Colony, Tajganj, Agra, Uttar Pradesh 282001, India',
  'monument',
  27.1751,
  78.0421,
  '/placeholder.svg?height=400&width=600',
  '/placeholder.svg?height=800&width=1200',
  '/placeholder.svg?height=400&width=600',
  4.8,
  2547,
  15234,
  50000,
  8932,
  ARRAY['Stunning Mughal architecture', 'UNESCO World Heritage Site', 'Symbol of eternal love', 'Intricate marble inlay work'],
  ARRAY['Use headphones for the best audio experience', 'Enable VR mode for full immersion', 'Visit during virtual sunset for stunning views', 'Explore the gardens and surrounding structures'],
  '[{"name": "Taj Mahal Souvenirs", "url": "https://example.com/shop"}, {"name": "Indian Handicrafts", "url": "https://example.com/crafts"}]'::jsonb,
  ARRAY['Popular', 'Featured', 'Top Rated'],
  true
);
